# Generated by Django 5.0 on 2023-12-15 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caissier',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='caissier',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
